### ISSUE TITLE
报错'NoneType' object has no attribute 'CreateField'

### ISSUE THREAD

**Issue by negunegi** [liujiao111/poi#6]
请问作者的的gdla版本是多少的？

**Comment by negunegi** [comment]
急急急

**Comment by negunegi** [comment]
还有一个ERROR 1: Failed to create file data\poi-440300-餐饮\poi-440300-餐饮-20.shp: No such file or directory

**Comment by negunegi** [comment]
但是数据倒是写进去了

**Comment by negunegi** [comment]
```
ERROR 1: Failed to create file data\poi-440300-餐饮\poi-440300-餐饮-20.shp: No such file or directory
Traceback (most recent call last):
  File "F:/project/poi/GAODE_REVIESED/gaode/poi-pology/app.py", line 255, in <module>
    get_data(city_code, type, coord)
  File "F:/project/poi/GAODE_REVIESED/gaode/poi-pology/app.py", line 247, in get_data
    trans_point_to_shp(file_folder, file_name, 0, 1, pology_split_distance, keyword)
  File "F:\project\poi\GAODE_REVIESED\gaode\poi-pology\shp.py", line 74, in trans_point_to_shp
    layer.CreateField(ogr.FieldDefn("lng", ogr.OFTReal))
AttributeError: 'NoneType' object has no attribute 'CreateField'
```

**Comment by negunegi** [comment]
把那个写入shp的给注释掉了解决了。博主的工具太好用了，表示感谢。
